Step 1
SergeyK2004/react-burger pull request #1
Opened 2021-07-24 20:31 UTC by SergeyK2004

2021-07-25 17:00 UTC, AygulMalikova requested changes
Отличная работа! 

У вас хорошо структурированный и чистый код, разделенный на компоненты.

Но есть небольшие рекомендации. В первую очередь прошу вас обратить внимание, что пулл-реквест должен быть создан из ветки `sprint-1/step-1` в `main`. И также, были оставлены другие комментарии и рекомендации по улучшению вашего кода.

Я напоминаю, что работа будет принята, как только все критические ошибки будут исправлены. Желаю вам удачи!

2021-07-25 17:00 UTC, AygulMalikova commented on src/components/BurgerConstructor/BurgerConstructor.module.css
> +.summ {
summ -> sum

2021-07-27 03:31 UTC, SergeyK2004 commented on src/components/BurgerConstructor/BurgerConstructor.module.css
> +.summ {
Мммм. 
Видимо неудачное название класса созвучное с имеющейся функцией.
Переделал. Подумал об этом еще когда писал, но что-то тогда в голову total не пришло. Наверное до сих пор об этом думаю, поэтому не вижу другой ошибки.

2021-07-27 03:33 UTC, SergeyK2004 commented
Айгуль, спасибо большое за комментарии и подсказки.
Не совсем понял с пулл-реквестом. Вроде я так и делал из step-1 в main  и так и написано в заголовке. Все остальное постарался исправить.

2021-07-27 03:36 UTC, SergeyK2004 commented on src/components/AppHeader/AppHeader.jsx
> +import React from 'react';
Согласно заданию в проектной работе названия даны в CamellCase 
Выдержка из задания:
Ваша задача — сверстать несколько компонентов главного экрана:
AppHeader — шапка приложения;
BurgerIngredients — список ингредиентов;
BurgerConstructor — текущий состав бургера.

2021-07-27 08:45 UTC, AygulMalikova commented
Ваша работа принята, я вас поздравляю! У вас отличный код, поделенный на компоненты. Так держать!
По поводу названия ветки. Сейчас у вас называется `step-1`, а должно быть `sprint-1/step-1`, т.к. в будущем у вас будут еще спринты с первым этапом, например, `sprint-3/step-1`. Поэтому важно добавить еще номер спринта. Имейте это ввиду на следующем этапе. Еще раз поздравляю и желаю вам дальнейших успехов!

2021-07-28 02:43 UTC, merged